version: 0.2

phases:
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
      - ls app/build/outputs/apk/debug
artifacts:
  files: 
     - './app/build/outputs/apk/debug/*.apk'
  discard-paths: yes
